# -*- coding: utf-8 -*-
"""make2Txt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SaXZgxQ0ChfL0fhDYG1QqH6MtTzCEbjz
"""

import os
import random


trainval_percent = 0.9
train_percent = 0.9
img_filepath = 'yolov5-master/data/images'
txtsavepath = 'yolov5-master/data/ImageSets'
datasavepath = 'data/images/'
total_xml = os.listdir(img_filepath)

num = len(total_xml)
list = range(num)
tv = int(num * trainval_percent)
tr = int(tv * train_percent)
trainval = random.sample(list, tv)
train = random.sample(trainval, tr)

#ImageSets
ftrainval = open(os.path.join(txtsavepath,'trainval.txt'), 'w')
ftest = open(os.path.join(txtsavepath,'test.txt'), 'w')
ftrain = open(os.path.join(txtsavepath,'train.txt'), 'w')
fval = open(os.path.join(txtsavepath,'val.txt'), 'w')

#data
dtest = open(os.path.join('yolov5-master/data','test.txt'), 'w')
dtrain = open(os.path.join('yolov5-master/data','train.txt'), 'w')
dval = open(os.path.join('yolov5-master/data','val.txt'), 'w')


for i in list:
    name = total_xml[i][:-4] + '\n'
    if i in trainval:
        ftrainval.write(name)
        if i in train:
            ftrain.write(name)
            dtrain.write(datasavepath + total_xml[i] + '\n')
        else:
            fval.write(name)
            dval.write(datasavepath +  total_xml[i] + '\n')
    else:
        ftest.write(name)
        dtest.write(datasavepath +  total_xml[i] + '\n')

ftrainval.close()
ftrain.close()
fval.close()
ftest.close()

dtrain.close()
dval.close()
dtest.close()